{
  "name": "Deploy application to AWS",
  "refId": "5",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},
  "clusters": [
    {
      "account": "development",
      "application": "oxletech",
      "associatePublicIpAddress": false,
      "availabilityZones": {
        "us-east-1": [
          "us-east-1a",
          "us-east-1b",
          "us-east-1c"
        ]
      },
      "base64UserData": "",
      "capacity": {
        "desired": 1,
        "max": 1,
        "min": 1
      },
      "cloudProvider": "aws",
      "cooldown": 10,
      "copySourceCustomBlockDeviceMappings": false,
      "dirty": {},
      "ebsOptimized": false,
      "enabledMetrics": [],
      "freeFormDetails": "",
      "healthCheckGracePeriod": 600,
      "healthCheckType": "EC2",
      "iamRole": "development-gonfalon",
      "instanceMonitoring": false,
      "instanceType": "t2.small",
      "keyPair": "ops_bootstrap",
      "loadBalancers": [],
      "moniker": {
        "app": "oxletech",
        "detail": "",
        "stack": "dev"
      },
      "provider": "aws",
      "securityGroups": [
        "sg-092580313f5be8060"
      ],
      "spelLoadBalancers": [],
      "spelTargetGroups": [],
      "spotPrice": "",
      "stack": "dev",
      "strategy": "",
      "subnetType": "private-subnets",
      "suspendedProcesses": [],
      "tags": {
        "Name": "oxletech (test)"
      },
      "targetGroups": [],
      "targetHealthyDeployPercentage": 100,
      "terminationPolicies": [
        "Default"
      ],
      "useAmiBlockDeviceMappings": false,
      "useSourceCapacity": false
    }
  ],
  "overrideTimeout": true,
  "stageTimeoutMs": 1800000,
  "type": "deploy"
}
