{
  "name": "Determine version of application currently deployed",
  "refId": "1",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},
  "completeOtherBranchesThenFail": false,
  "continuePipeline": true,
  "failPipeline": false,
  "method": "GET",
  "overrideTimeout": true,
  "progressJsonPath": "",
  "stageTimeoutMs": 60000,
  "statusJsonPath": "",
  "statusUrlResolution": "getMethod",
  "successStatuses": "",
  "type": "webhook",
  "url": "https://internal.stage/private/status",
  "waitForCompletion": false
}
